In [4]:
from google.colab import drive
drive.mount('/content/gdrive')

ModuleNotFoundError: No module named 'google.colab'

In [4]:
pip install sktime

Note: you may need to restart the kernel to use updated packages.


In [5]:
import os
import sktime
from sktime.datasets import load_from_tsfile

In [6]:
X, y = load_from_tsfile('/Users/PRADEEP SHETTY/Desktop/IEEE internship/data_final.ts',return_data_type="numpy3d")

In [8]:
print(X.shape)

(629, 1, 24)


In [9]:
print(X)

[[[  3.17   3.     3.2  ...   3.     4.47  83.45]]

 [[  0.     0.     0.   ...   0.     0.     0.  ]]

 [[ 68.75  24.15  34.22 ...  41.43  75.58  45.27]]

 ...

 [[  0.     0.     0.   ...   0.     0.     0.  ]]

 [[ 25.3   16.17   1.75 ... 189.75 723.52 344.92]]

 [[341.02 255.58 506.85 ...   0.     0.     0.  ]]]


In [10]:
print(X[298])

[[3.   3.   3.   3.   3.   3.   3.   3.   3.   3.   3.   3.   3.   3.
  3.   3.   2.08 0.   0.   0.   0.05 1.   2.9  3.  ]]


In [11]:
print(X.shape)

(629, 1, 24)


In [12]:
X1= X.reshape(X.shape[0], (X.shape[1]*X.shape[2]))
print("Original array:\n",X.shape )
print("Reshaped array:\n",X1.shape)

Original array:
 (629, 1, 24)
Reshaped array:
 (629, 24)


In [13]:
print(X1)

[[  3.17   3.     3.2  ...   3.     4.47  83.45]
 [  0.     0.     0.   ...   0.     0.     0.  ]
 [ 68.75  24.15  34.22 ...  41.43  75.58  45.27]
 ...
 [  0.     0.     0.   ...   0.     0.     0.  ]
 [ 25.3   16.17   1.75 ... 189.75 723.52 344.92]
 [341.02 255.58 506.85 ...   0.     0.     0.  ]]


In [14]:
print(y[298])

0


In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,random_state=42)

In [16]:
print(X_train)

[[[2.3600e+01 7.0300e+00 5.2500e+00 ... 4.4800e+01 6.4193e+02 4.1742e+02]]

 [[1.6370e+01 5.3700e+00 1.1300e+00 ... 3.3007e+02 2.5835e+02 3.5072e+02]]

 [[1.0700e+00 9.6700e+00 5.3700e+00 ... 1.3492e+02 1.9915e+02 1.1068e+02]]

 ...

 [[1.8000e-01 6.6500e+00 3.1000e+00 ... 1.0493e+02 2.0197e+02 1.8592e+02]]

 [[0.0000e+00 0.0000e+00 0.0000e+00 ... 0.0000e+00 0.0000e+00 0.0000e+00]]

 [[3.0635e+02 8.3230e+01 1.3533e+02 ... 2.9322e+02 1.6388e+02 8.4030e+01]]]


In [17]:
print(y_train)

['0' '0' '1' '0' '1' '1' '1' '0' '1' '1' '1' '0' '0' '0' '0' '1' '1' '0'
 '0' '0' '0' '1' '1' '1' '1' '1' '1' '0' '1' '1' '1' '0' '1' '0' '1' '0'
 '0' '1' '1' '0' '1' '0' '0' '0' '0' '1' '0' '1' '1' '1' '1' '1' '1' '1'
 '0' '1' '0' '0' '0' '0' '1' '0' '0' '0' '1' '1' '1' '1' '1' '1' '0' '1'
 '0' '1' '0' '0' '0' '1' '0' '0' '1' '0' '0' '1' '1' '1' '0' '1' '0' '0'
 '0' '0' '0' '0' '1' '1' '0' '0' '1' '0' '0' '0' '0' '0' '1' '1' '1' '0'
 '0' '1' '0' '0' '0' '0' '1' '0' '1' '1' '1' '0' '1' '1' '1' '0' '1' '1'
 '1' '0' '1' '0' '0' '1' '0' '0' '0' '1' '1' '0' '0' '0' '0' '1' '1' '0'
 '0' '0' '1' '1' '0' '0' '1' '0' '0' '0' '0' '0' '0' '1' '1' '0' '1' '1'
 '1' '1' '1' '1' '0' '1' '0' '0' '1' '0' '0' '0' '0' '1' '0' '1' '0' '1'
 '0' '1' '0' '1' '0' '0' '1' '0' '0' '1' '0' '1' '0' '0' '1' '0' '0' '0'
 '1' '0' '0' '0' '0' '1' '0' '1' '1' '1' '0' '0' '0' '1' '1' '0' '0' '0'
 '1' '0' '0' '1' '1' '0' '0' '0' '1' '0' '0' '1' '0' '0' '1' '0' '0' '1'
 '0' '0' '0' '0' '1' '0' '1' '1' '1' '0' '0' '1' '0

### Rocket Classifier

In [18]:
from sktime.classification.kernel_based import RocketClassifier

classifier = RocketClassifier()

classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

print(y_pred)

from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

['0' '1' '0' '1' '0' '0' '0' '1' '0' '0' '1' '1' '1' '1' '1' '1' '1' '1'
 '0' '0' '1' '1' '0' '0' '1' '0' '0' '0' '0' '0' '1' '0' '0' '1' '1' '1'
 '0' '0' '1' '0' '0' '1' '0' '0' '0' '0' '1' '1' '0' '0' '0' '1' '0' '1'
 '1' '1' '1' '0' '0' '1' '1' '0' '1' '1' '1' '0' '0' '1' '0' '0' '1' '1'
 '1' '0' '1' '1' '0' '1' '0' '0' '0' '0' '0' '1' '0' '1' '0' '0' '1' '1'
 '0' '1' '1' '1' '0' '1' '1' '1' '1' '0' '1' '0' '0' '1' '0' '1' '1' '1'
 '0' '0' '1' '1' '0' '0' '0' '1' '0' '1' '1' '0' '1' '1' '0' '1' '0' '0'
 '0' '1' '1' '1' '1' '1' '1' '1' '0' '0' '1' '0' '1' '0' '0' '1' '1' '0'
 '1' '1' '1' '1' '0' '0' '0' '1' '1' '0' '0' '0' '0' '0']


0.6772151898734177

### TimeSeriesForestClassifier

In [62]:
from sktime.classification.interval_based import TimeSeriesForestClassifier

In [63]:
clf = TimeSeriesForestClassifier(n_estimators=5)
clf.fit(X_train, y_train)

TimeSeriesForestClassifier(n_estimators=5)

In [57]:
y_pred3 = clf.predict(X_test)


In [58]:
print(y_pred3)

['1' '1' '0' '1' '1' '0' '1' '1' '0' '1' '0' '0' '0' '0' '1' '1' '1' '1'
 '0' '0' '1' '1' '1' '1' '0' '1' '0' '0' '0' '0' '1' '0' '1' '1' '1' '0'
 '0' '0' '1' '1' '1' '1' '1' '0' '0' '0' '0' '1' '0' '0' '1' '1' '0' '1'
 '0' '1' '1' '0' '1' '1' '0' '1' '0' '1' '1' '0' '1' '0' '0' '0' '1' '1'
 '0' '1' '1' '1' '0' '1' '1' '0' '0' '1' '0' '1' '0' '1' '1' '1' '0' '1'
 '0' '0' '1' '1' '0' '0' '1' '1' '1' '0' '1' '0' '0' '0' '1' '1' '1' '1'
 '1' '0' '1' '1' '0' '1' '1' '1' '1' '1' '1' '1' '1' '1' '0' '1' '0' '0'
 '0' '1' '1' '1' '1' '0' '1' '0' '0' '0' '0' '0' '0' '0' '0' '0' '1' '0'
 '0' '1' '0' '0' '0' '0' '0' '0' '1' '0' '0' '0' '1' '0']


In [59]:
print(y_test)

['0' '1' '0' '1' '0' '0' '0' '1' '0' '1' '0' '1' '1' '1' '0' '1' '1' '0'
 '1' '0' '1' '1' '1' '0' '0' '1' '1' '0' '0' '0' '1' '0' '1' '1' '1' '0'
 '0' '0' '1' '0' '0' '1' '1' '0' '0' '1' '0' '0' '1' '0' '1' '1' '1' '1'
 '0' '1' '1' '0' '1' '1' '0' '0' '0' '1' '1' '1' '1' '0' '0' '0' '1' '1'
 '1' '0' '1' '0' '0' '1' '0' '0' '0' '1' '0' '0' '1' '0' '1' '1' '1' '1'
 '0' '0' '1' '1' '1' '0' '1' '1' '1' '0' '1' '0' '0' '0' '0' '1' '1' '1'
 '1' '0' '1' '0' '1' '0' '0' '1' '0' '1' '1' '1' '1' '0' '0' '1' '0' '0'
 '0' '1' '1' '1' '0' '1' '1' '0' '0' '0' '0' '0' '0' '0' '0' '0' '1' '1'
 '0' '1' '1' '1' '0' '0' '0' '0' '1' '0' '0' '1' '1' '0']


In [60]:
accuracy_score(y_test, y_pred3)

0.740506329113924

### CNN Classifier

In [64]:
from sktime.classification.deep_learning.cnn import CNNClassifier

In [65]:

cnn = CNNClassifier(n_epochs=20,batch_size=4)

In [66]:
cnn.fit(X_train, y_train)

C:\Users\PRADEEP SHETTY\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


CNNClassifier(batch_size=4, n_epochs=20)

In [67]:
y_pred2 = cnn.predict(X_test)

40/40 [==============================] - 0s 1ms/step


In [68]:
accuracy_score(y_test, y_pred2)

0.5949367088607594

### SupervisedTimeSeriesForest

In [75]:
from sktime.classification.interval_based import SupervisedTimeSeriesForest

In [76]:
clf = SupervisedTimeSeriesForest(n_estimators=5)
clf.fit(X_train, y_train)

SupervisedTimeSeriesForest(n_estimators=5)

In [77]:
y_pred4 = clf.predict(X_test)

In [72]:
accuracy_score(y_test, y_pred4)

0.7215189873417721

### PYTS RandomForest Classification

In [73]:
pip install pyts

                                              0.0/2.5 MB ? eta -:--:--
     -                                        0.1/2.5 MB 1.3 MB/s eta 0:00:02
     ---                                      0.2/2.5 MB 2.4 MB/s eta 0:00:01
     -----                                    0.4/2.5 MB 2.9 MB/s eta 0:00:01
     ---------                                0.6/2.5 MB 3.1 MB/s eta 0:00:01
     ------------                             0.8/2.5 MB 3.3 MB/s eta 0:00:01
     ---------------                          1.0/2.5 MB 3.6 MB/s eta 0:00:01
     ----------------                         1.0/2.5 MB 3.5 MB/s eta 0:00:01
     -----------------                        1.1/2.5 MB 3.0 MB/s eta 0:00:01
     --------------------                     1.3/2.5 MB 3.0 MB/s eta 0:00:01
     -----------------------                  1.5/2.5 MB 3.2 MB/s eta 0:00:01
     ---------------------------              1.7/2.5 MB 3.3 MB/s eta 0:00:01
     -----------------------------            1.9/2.5 MB 3.5 MB/s eta 0

In [74]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
from os import listdir
import glob
import os
from natsort import natsorted
from keras.preprocessing import sequence
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM

from keras.optimizers import Adam
from keras.models import load_model
from keras.callbacks import ModelCheckpoint


ModuleNotFoundError: No module named 'natsort'

In [ ]:
# base_dir = '/content/gdrive/MyDrive/IEEE/data/exp'
# count=0
# sequences=list()
# file_list = [os.path.basename(x) for x in glob.glob(base_dir+"/*.csv")]
# file_list = natsorted(file_list)
# print(file_list)
# for file in file_list:
#             count+=1
#             df=pd.read_csv("/content/gdrive/MyDrive/IEEE/data/exp/"+file,header=0)
#             values = df['Avg_activity'].values
#             # print(values)
#             sequences.append(values)



In [ ]:
# from keras.utils import pad_sequences

# seq_len = 500
# final_seq=pad_sequences(sequences, maxlen=seq_len, padding='post', dtype='float', truncating='post')

In [ ]:
# print(type(final_seq))

In [ ]:
# print(final_seq.shape)

In [80]:
 pip install tslearn

Note: you may need to restart the kernel to use updated packages.


In [81]:
from tslearn.utils import to_pyts_dataset

In [82]:
pyts_arr = to_pyts_dataset(X1)

In [83]:
print(pyts_arr)

[[  3.17   3.     3.2  ...   3.     4.47  83.45]
 [  0.     0.     0.   ...   0.     0.     0.  ]
 [ 68.75  24.15  34.22 ...  41.43  75.58  45.27]
 ...
 [  0.     0.     0.   ...   0.     0.     0.  ]
 [ 25.3   16.17   1.75 ... 189.75 723.52 344.92]
 [341.02 255.58 506.85 ...   0.     0.     0.  ]]


In [84]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(pyts_arr, y,random_state=42)

In [85]:
import numpy as np
from pyts.datasets import load_gunpoint
from pyts.classification import TimeSeriesForest
import matplotlib.pyplot as plt

# X_train, X_test, y_train, y_test = load_gunpoint(return_X_y=True)
clf = TimeSeriesForest(random_state=43)
clf.fit(X_train, y_train)

TimeSeriesForest(random_state=43)

In [86]:
y_pred5 = clf.predict(X_test)

In [87]:
accuracy_score(y_test, y_pred5)

0.7531645569620253

In [88]:
print(y_test)

['0' '1' '0' '1' '0' '0' '0' '1' '0' '1' '0' '1' '1' '1' '0' '1' '1' '0'
 '1' '0' '1' '1' '1' '0' '0' '1' '1' '0' '0' '0' '1' '0' '1' '1' '1' '0'
 '0' '0' '1' '0' '0' '1' '1' '0' '0' '1' '0' '0' '1' '0' '1' '1' '1' '1'
 '0' '1' '1' '0' '1' '1' '0' '0' '0' '1' '1' '1' '1' '0' '0' '0' '1' '1'
 '1' '0' '1' '0' '0' '1' '0' '0' '0' '1' '0' '0' '1' '0' '1' '1' '1' '1'
 '0' '0' '1' '1' '1' '0' '1' '1' '1' '0' '1' '0' '0' '0' '0' '1' '1' '1'
 '1' '0' '1' '0' '1' '0' '0' '1' '0' '1' '1' '1' '1' '0' '0' '1' '0' '0'
 '0' '1' '1' '1' '0' '1' '1' '0' '0' '0' '0' '0' '0' '0' '0' '0' '1' '1'
 '0' '1' '1' '1' '0' '0' '0' '0' '1' '0' '0' '1' '1' '0']


In [89]:
print(y_pred5)

['0' '1' '0' '1' '0' '0' '1' '1' '0' '1' '0' '1' '0' '0' '1' '1' '1' '1'
 '0' '0' '1' '0' '0' '1' '0' '1' '0' '0' '0' '0' '1' '0' '1' '1' '1' '0'
 '0' '0' '1' '1' '1' '1' '1' '0' '0' '0' '1' '1' '0' '0' '1' '1' '0' '1'
 '1' '1' '1' '0' '1' '1' '0' '0' '0' '1' '1' '0' '1' '0' '0' '0' '1' '0'
 '0' '0' '1' '1' '0' '1' '1' '0' '0' '1' '0' '1' '1' '1' '1' '1' '1' '1'
 '0' '0' '1' '1' '0' '0' '1' '1' '1' '0' '0' '0' '0' '0' '1' '1' '1' '1'
 '0' '0' '1' '1' '0' '0' '0' '1' '1' '1' '1' '1' '1' '0' '0' '0' '0' '0'
 '0' '0' '1' '1' '0' '0' '1' '0' '0' '0' '0' '0' '0' '0' '0' '0' '1' '0'
 '0' '1' '0' '0' '0' '0' '0' '0' '1' '0' '0' '0' '1' '0']


### Learning Shapelets

In [93]:
import matplotlib.pyplot as plt
import numpy as np
from pyts.classification import LearningShapelets
from pyts.datasets import load_gunpoint
from pyts.utils import windowed_view

In [94]:
clf = LearningShapelets(random_state=42, tol=0.01)
clf.fit(X_train, y_train)

LearningShapelets(random_state=42, tol=0.01)

In [95]:
y_pred6 = clf.predict(X_test)

In [96]:
accuracy_score(y_test, y_pred6)

0.41139240506329117

### Bag_of_features

In [97]:
import numpy as np
from pyts.datasets import load_gunpoint
from pyts.classification import TSBF
import matplotlib.pyplot as plt

# X_train, X_test, y_train, y_test = load_gunpoint(return_X_y=True)
clf = TSBF(random_state=43, bins=5)
clf.fit(X_train, y_train)

TSBF(bins=5, random_state=43)

In [98]:
y_pred7 = clf.predict(X_test)

In [99]:
accuracy_score(y_test, y_pred7)

0.6518987341772152

### BOSSVS

In [100]:
from pyts.classification import BOSSVS
bossvs = BOSSVS(word_size=2, n_bins=3, window_size=10)
bossvs.fit(X_train, y_train)

BOSSVS(n_bins=3, word_size=2)

In [101]:
y_pred8 = clf.predict(X_test)
accuracy_score(y_test, y_pred8)

0.6518987341772152